# Generated by Django 4.2.7 on 2024-09-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_rename_problems_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
