# Generated by Django 4.2.7 on 2024-09-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_author_alter_problem_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='input_description',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_description',
        ),
        migrations.AddField(
            model_name='problem',
            name='input_type',
            field=models.CharField(default='stdin', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='output_type',
            field=models.CharField(default='stdout', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1),
        ),
    ]
