# Generated by Django 4.2.7 on 2024-09-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_problem_input_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputoutput',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
