# Generated by Django 5.1.1 on 2024-09-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_solveddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='solveddata',
            name='source_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
