# Generated by Django 5.1.1 on 2024-09-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_solveddata_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='solveddata',
            name='language',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
