# Generated by Django 5.1.1 on 2024-09-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_solveddata_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='solveddata',
            name='run_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
