# Generated by Django 5.1.1 on 2024-09-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_solveddata_run_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solveddata',
            old_name='solved_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='solveddata',
            name='verdict',
            field=models.CharField(default='Accepted', max_length=255),
            preserve_default=False,
        ),
    ]
