# Generated by Django 4.2.7 on 2024-09-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_city_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='t_shirt_size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
