# Generated by Django 4.2.7 on 2024-09-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.post'),
        ),
    ]
