# Generated by Django 4.2.7 on 2024-09-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_inputoutput_is_public'),
        ('contests', '0002_contestproblem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestproblem',
            name='all_problems',
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='all_problems',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
            preserve_default=False,
        ),
    ]
