# Generated by Django 5.1.1 on 2024-09-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_remove_contestproblem_all_problems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registered_users',
            field=models.IntegerField(default=0),
        ),
    ]
